"""Add image_url

Revision ID: 80b1780b4174
Revises: 
Create Date: 2026-02-21 18:57:40.316036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '80b1780b4174'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=100), nullable=False),
    sa.Column('surname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('BuildVersion')
    op.drop_table('ErrorLog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ErrorLog',
    sa.Column('ErrorLogID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('ErrorTime', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.Column('UserName', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('ErrorNumber', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ErrorSeverity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ErrorState', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ErrorProcedure', sa.NVARCHAR(length=126, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('ErrorLine', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ErrorMessage', sa.NVARCHAR(length=4000, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('ErrorLogID', name=op.f('PK_ErrorLog_ErrorLogID'))
    )
    op.create_table('BuildVersion',
    sa.Column('SystemInformationID', mssql.TINYINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Database Version', sa.NVARCHAR(length=25, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('VersionDate', sa.DATETIME(), autoincrement=False, nullable=False),
    sa.Column('ModifiedDate', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('SystemInformationID', name=op.f('PK__BuildVer__35E58ECA3EA7052A'))
    )
    op.drop_table('person')
    # ### end Alembic commands ###
